#cloud-config
autoinstall:
  version: 1
  network:
    network:
      version: 2
      ethernets:
        ens33:
          dhcp4: true
      bridges:
        br0:
          dhcp4: true
          interfaces:
            - ens33
  storage:
    layout:
      name: lvm
      sizing-policy: all
  packages:
    - bzip2
    - ca-certificates
    - curl
    - file
    - jq
    - lsb
    - unzip
  ssh:
    install-server: true
    allow-pw: true
  late-commands:
    - curtin in-target -- sed -ie 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=30/' /etc/default/grub
    - curtin in-target -- sed -ie 's/GRUB_TIMEOUT_STYLE=.*/GRUB_TIMEOUT=countdown/' /etc/default/grub
    - curtin in-target -- sed -ie 's/GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX="console=tty0 console=ttyS4,115200n8 systemd.wants=serial-getty@ttyS4"/' /etc/default/grub
    - curtin in-target -- sed -ie 's/#GRUB_TERMINAL=.*/GRUB_TERMINAL="console"/' /etc/default/grub
    - curtin in-target -- update-grub
  user-data: # cloud-init starts here
    hostname: robot00
    users:
      - name: automat
        uid: 63112
        primary_group: users
        groups: users
        shell: /bin/bash
        plain_text_passwd: superseekret
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINy9cJcJl8oN6bRtcBc4RZq8f/T6P1AFR3YS1YRYi5YY sheila
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEV40AiHWQUCXY7Yh3s5Vj/ZtRc1BWex6D2+eoEnRXM7 mahowald
    chpasswd: {expire: false}
    ssh_pwauth: true
